trigger:
  branches:
    include:
      - workbench  # Trigger the pipeline on the workbench branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'langflow-app'
  dockerHubRepository: 'kendralabs/workbench-azure'

steps:
  - task: DockerCompose@1
    displayName: 'Build Docker Images'
    inputs:
      containerregistrytype: 'Container Registry'  # Specify the container registry type
      dockerRegistryEndpoint: 'docker'  # Name of your Docker service connection
      dockerComposeFile: '**/dev.docker-compose.yml'  # Path to your Docker Compose file
      projectName: 'langflow'  # Valid project name (lowercase, alphanumeric, hyphen, or underscore)
      action: 'Build services'  # Build the services defined in the Docker Compose file
      includeSourceTags: true  # Include source tags in the built images
      includeLatestTag: true  # Include the "latest" tag for the images

  # Step 2: Push Docker images to the container registry
  - task: DockerCompose@1
    displayName: 'Push Docker Images'
    inputs:
      containerregistrytype: 'Container Registry'  # Specify the container registry type
      dockerRegistryEndpoint: 'docker'  # Name of your Docker service connection
      dockerComposeFile: '**/dev.docker-compose.yml'  # Path to your Docker Compose file
      projectName: 'langflow'  # Valid project name (lowercase, alphanumeric, hyphen, or underscore)
      action: 'Push services'  # Push the built services (images) to the container registry
      includeSourceTags: true  # Include source tags in the pushed images
      includeLatestTag: true
  # Step 3: Deploy Containers Using Docker Compose
  - task: SSH@0
    displayName: 'Deploy Docker Containers'
    inputs:
      sshEndpoint: 'ssh'  # Your SSH service connection
      runOptions: 'inline'
      inline: |
        # Navigate to the directory containing the Docker Compose file
        cd /home/azureuser/langflow || exit 1
        
        # Pull the latest images
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml pull
        
        # Stop and remove old containers
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml down
        
        # Start containers with new images
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml up -d
        
        echo "Deployment completed successfully."
