trigger:
  branches:
    include:
      - workbench-qa  # Trigger the pipeline on dev branch (workbench-qa)

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'langflow-app'

steps:
  - task: SSH@0
    displayName: 'Clean Up and Deploy Using Docker Compose'
    inputs:
      sshEndpoint: 'ssh'  # Use the SSH service connection name
      runOptions: 'inline'
      inline: |
        # Navigate to the deployment directory
        cd /home/azureuser/langflow || exit 1

        # Ensure the correct branch and pull the latest changes
        echo "Switching to dev branch and fetching updates..."
        git fetch origin workbench-qa
        git checkout workbench-qa || git checkout -b workbench-qa origin/workbench-qa
        git reset --hard origin/workbench-qa

        # Stop and remove dev-related containers
        echo "Removing dev containers..."
        docker ps -aq -f name=dev-langflow | xargs -r docker rm -f || echo "No dev containers to remove."

        # Remove dev-related Docker images
        echo "Removing dev images..."
        docker images -aq -f reference=dev-langflow | xargs -r docker rmi -f || echo "No dev images to remove."

        # Clean up unused data
        echo "Performing system prune..."
        docker system prune -f

        # Rebuild and start the containers for dev
        echo "Starting dev environment..."
        docker-compose -f docker/dev.docker-compose.yml up --build -d

        # Wait for the containers to stabilize
        echo "Waiting for containers to stabilize..."
        sleep 10

        # Reload Nginx to apply changes
        echo "Reloading Nginx..."
        sudo nginx -t > /dev/null 2>&1
        sudo systemctl reload nginx > /dev/null 2>&1  

        # Verify if the dev containers are running
        running_containers=$(docker ps -q -f name=dev-langflow)

        if [ -n "$running_containers" ]; then
          echo "Dev containers are running successfully."
          exit 0  # Success
        else
          echo "Dev containers are not running."
          exit 1  # Failure
        fi
