trigger:
  branches:
    include:
      - workbench  # Trigger the pipeline on the workbench branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'langflow-app'
  dockerHubRepository: 'kendralabs/workbench-azure'

steps:
  # Step 1: Build Docker Images using Docker Compose
  - task: DockerCompose@1
    displayName: 'Build Docker Images'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker'  # Your Docker service connection
      dockerComposeFile: '**/dev.docker-compose.yml'  # Path to your Docker Compose file
      action: 'Build services'
      buildImages: true
      tags: '$(Build.BuildId)'  # Tag with the build ID

  # Step 2: Push Docker Images to Docker Hub
  - task: Docker@2
    displayName: 'Push Docker Images to Docker Hub'
    inputs:
      command: 'push'
      containerRegistry: 'docker'  # Docker service connection
      repository: $(dockerHubRepository)  # Docker Hub repository
      tags: '$(Build.BuildId)'  # Tag with build ID

  # Step 3: Deploy Containers Using Docker Compose
  - task: SSH@0
    displayName: 'Deploy Docker Containers'
    inputs:
      sshEndpoint: 'ssh'  # Your SSH service connection
      runOptions: 'inline'
      inline: |
        # Navigate to the directory containing the Docker Compose file
        cd /home/azureuser/langflow || exit 1
        
        # Pull the latest images
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml pull
        
        # Stop and remove old containers
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml down
        
        # Start containers with new images
        docker-compose -f /home/azureuser/langflow/docker/dev.docker-compose.yml up -d
        
        echo "Deployment completed successfully."
