services:
  langflow-backend:
    image: kendralabs/workbench-backend:1.3.5 # or another version tag on https://hub.docker.com/r/langflowai/langflow
    #pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    environment:
      #- LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@localhost:5432/langflow
      - LANGFLOW_DATABASE_URL=postgresql://sandboxuser:sandboxuser123@workbench-db.postgres.database.azure.com:5432/workbenchsandbox
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=superadmin
      - LANGFLOW_SUPERUSER_PASSWORD=superadmin
    volumes:
      - langflow-data:/app/langflow
  langflow-frontend:
    image: langflow_frontend:1.3.5 # or another version tag on https://hub.docker.com/r/langflowai/
    depends_on:
      - langflow-backend
    environment:
      - BACKEND_URL=http://langflow-backend:7860
    #pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "80:80"   
volumes:
  langflow-data:
